In [ ]:
import numpy as np

In [ ]:
np.array([[1,2,3],[2,3,4]])

array([[1, 2, 3],
       [2, 3, 4]])

In [ ]:
np.zeros((6,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
a = np.ones((5,5))
b = np.ones((5,5))
print()
print (a)



[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
a+b

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [ ]:
np.sin(a)

array([[0.84147098, 0.84147098, 0.84147098, 0.84147098, 0.84147098],
       [0.84147098, 0.84147098, 0.84147098, 0.84147098, 0.84147098],
       [0.84147098, 0.84147098, 0.84147098, 0.84147098, 0.84147098],
       [0.84147098, 0.84147098, 0.84147098, 0.84147098, 0.84147098],
       [0.84147098, 0.84147098, 0.84147098, 0.84147098, 0.84147098]])

In [ ]:
a.max(axis=1)

array([1., 1., 1., 1., 1.])

In [ ]:
a = np.array([[1,2],[2,5]])
np.linalg.inv(a)

array([[ 5., -2.],
       [-2.,  1.]])

In [33]:
import numpy as np


empty_array = np.empty((2, 2))
print("Empty Array:\n", empty_array)


ones_array = np.ones((4, 2))
print("\nAll-One Array:\n", ones_array)

filled_array = np.full((3, 3), 7)
print("\nFilled Array:\n", filled_array)

zeros_like_array = np.zeros_like(filled_array)
print("\nZeros Like Array:\n", zeros_like_array)


ones_like_array = np.ones_like(filled_array)
print("\nOnes Like Array:\n", ones_like_array)


new_list = [1, 2, 3, 4]
array_from_list = np.array(new_list)
print("\nArray from list:\n", array_from_list)


Empty Array:
 [[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]]

All-One Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Filled Array:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros Like Array:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]

Ones Like Array:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]

Array from list:
 [1 2 3 4]


In [34]:
arr_range = np.arange(10, 50)
print("Array from 10 to 49:\n", arr_range)

matrix_3x3 = np.arange(9).reshape((3, 3))
print("\n3x3 Matrix:\n", matrix_3x3)

identity_3x3 = np.eye(3)
print("\nIdentity Matrix:\n", identity_3x3)

rand_arr = np.random.random(30)
print("\nRandom Array:\n", rand_arr)
print("Mean:", rand_arr.mean())

rand_10x10 = np.random.random((10, 10))
print("\nMin:", rand_10x10.min(), "Max:", rand_10x10.max())

zero_array = np.zeros(10)
zero_array[4] = 1
print("\nModified Zero Array:\n", zero_array)

arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\nReversed Array:\n", reversed_arr)

# 8. 2D array with 1 on border and 0 inside
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\n2D Array with border 1s:\n", border_array)

checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\nCheckerboard Pattern:\n", checkerboard)


Array from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 Matrix:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random Array:
 [0.25596239 0.6239631  0.83247026 0.31290479 0.17391842 0.2245412
 0.18064632 0.75869432 0.4195113  0.16387012 0.1484334  0.97536012
 0.13623449 0.65024339 0.55388342 0.19409371 0.81819603 0.02080307
 0.69267423 0.11288888 0.00563845 0.23364282 0.06349793 0.52769868
 0.29223784 0.62059969 0.47242781 0.60856081 0.0100984  0.87349419]
Mean: 0.3985729855615776

Min: 0.011931660650135179 Max: 0.9939517805554133

Modified Zero Array:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

Reversed Array:
 [0 4 0 0 2 1]

2D Array with border 1s:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

Checkerboard Pattern:
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 

In [35]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

print("x + y:\n", x + y)

print("x - y:\n", x - y)

print("x * 3:\n", x * 3)

print("x^2:\n", x**2)

print("v.w:", np.dot(v, w))
print("x.v:", np.dot(x, v))
print("x.y:\n", np.dot(x, y))

print("x and y along row:\n", np.concatenate((x, y), axis=0))
print("v and w along column:\n", np.vstack((v, w)))


x + y:
 [[ 6  8]
 [10 13]]
x - y:
 [[-4 -4]
 [-4 -3]]
x * 3:
 [[ 3  6]
 [ 9 15]]
x^2:
 [[ 1  4]
 [ 9 25]]
v.w: 219
x.v: [29 77]
x.y:
 [[19 22]
 [50 58]]
x and y along row:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
v and w along column:
 [[ 9 10]
 [11 12]]


In [30]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. A * A^-1 = I
A_inv = np.linalg.inv(A)
print("A * A^-1:\n", np.dot(A, A_inv))

# 2. AB != BA
print("AB:\n", np.dot(A, B))
print("BA:\n", np.dot(B, A))

# 3. (AB)^T = B^T A^T
print("Transpose check:\n", np.dot(A, B).T)
print("B^T A^T:\n", np.dot(B.T, A.T))

# Solve system of equations
# 2x - 3y + z = -1
# x - y + 2z = -3
# 3x + y - z = 9

coeff = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
const = np.array([-1, -3, 9])
solution = np.linalg.inv(coeff).dot(const)
print("Solution:\n", solution)


A * A^-1:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
Transpose check:
 [[23 51]
 [13 29]]
B^T A^T:
 [[23 51]
 [13 29]]
Solution:
 [ 2.  1. -2.]


In [31]:
import time

size = 1000000

# Python lists
list1 = list(range(size))
list2 = list(range(size))

# Numpy arrays
np1 = np.array(list1)
np2 = np.array(list2)

# 1. Element-wise addition
start = time.time()
py_add = [a + b for a, b in zip(list1, list2)]
print("Python list addition time:", time.time() - start)

start = time.time()
np_add = np1 + np2
print("Numpy addition time:", time.time() - start)

# 2. Element-wise multiplication
start = time.time()
py_mul = [a * b for a, b in zip(list1, list2)]
print("Python list multiplication time:", time.time() - start)

start = time.time()
np_mul = np1 * np2
print("Numpy multiplication time:", time.time() - start)

# 3. Dot product
start = time.time()
py_dot = sum(a*b for a, b in zip(list1, list2))
print("Python list dot product time:", time.time() - start)

start = time.time()
np_dot = np.dot(np1, np2)
print("Numpy dot product time:", time.time() - start)

# 4. Matrix multiplication 1000x1000
size_mat = 1000
py_mat1 = [list(range(size_mat)) for _ in range(size_mat)]
py_mat2 = [list(range(size_mat)) for _ in range(size_mat)]
np_mat1 = np.array(py_mat1)
np_mat2 = np.array(py_mat2)

start = time.time()
# Using pure Python nested loops (very slow!)
py_result = [[sum(a*b for a,b in zip(row,col)) for col in zip(*py_mat2)] for row in py_mat1]
print("Python list matrix multiplication time:", time.time() - start)

start = time.time()
np_result = np.dot(np_mat1, np_mat2)
print("Numpy matrix multiplication time:", time.time() - start)


Python list addition time: 0.32573628425598145
Numpy addition time: 0.01203012466430664
Python list multiplication time: 0.39374327659606934
Numpy multiplication time: 0.031235694885253906
Python list dot product time: 0.36316466331481934
Numpy dot product time: 0.0023965835571289062
Python list matrix multiplication time: 201.23059558868408
Numpy matrix multiplication time: 5.046957731246948
